### ISSUE TITLE
Caching does not happen for an object's newly added methods

### ISSUE THREAD

**Issue by maxsokolovsky** [yegor256/tacky#12]
A Tacky instance only caches results of those methods that are defined on an object at a single point - when a new Tacky instance is created.
When I add a new method to the object and call it, the Tacky instance does not cache the value. Is this by design?

**Comment by yegor256** [comment]
@maxsokolovsky I believe, it's by design, but I'm not sure. Can you please post the code you have in mind?

**Comment by maxsokolovsky** [comment]
Sure, here is an example.

```
require 'tacky'

obj = Object.new

def obj.answer
  sleep 2
  42
end

obj = Tacky.new(obj)

puts obj.answer # takes two seconds
puts obj.answer # instantaneous 

def obj.another_answer
  sleep 2
  42
end

puts obj.another_answer # takes two seconds
puts obj.another_answer # still takes two seconds
```

My singleton object gained a new method, but Tacky seems to ignore it.

**Comment by maxsokolovsky** [comment]
Never mind, this is my fault. I am defining `another_answer` on a different object `obj` - one returned by `Tacky.new`, not the original `obj`.
If I bind the Tacky instance to a different name, like `t = Tacky.new(obj)`, and define `another_answer` still on the `obj`, then `t.another_answer` will cache the returned value of the new method properly after the first call.
